//! RFC 9309 robots.txt, AIPREF `Content-Usage`, and the fetch outcome rules.
//!
//! Specified in `docs/spec/07-politeness-and-identity.md` section 7.4. The
//! happy path here is an afternoon's work. The reason this is a milestone is
//! everything around it: what a 503 means, what a 404 means, what happens when
//! the file is 40 MB of generated garbage, and which group applies when a site
//! names five user agents and one of them is a prefix of another.
//!
//! Every one of those has a wrong answer that looks like it works. Treating a
//! 503 as "no rules, crawl away" is the wrong answer that hammers a site
//! exactly when it is already failing, and it is what a naive implementation
//! does, so [`Robots::for_status`] exists to make the decision impossible to
//! skip.
//!
//! The robots decision belongs to the coordinator and never to the fetcher.
//! Doc 04 makes a disallowed URL unleaseable, so a community fetcher does not
//! need a parser here and cannot make us impolite through a bug in one.
//!
//! # What this is checked against
//!
//! `tests/conformance.rs` is Google's `robots_test.cc` transpiled, all 145 of
//! its decision assertions, regenerated by
//! `scripts/transpile-robots-conformance.py`. That suite is the reference the
//! RFC authors wrote alongside the document, so passing it is the difference
//! between claiming to implement RFC 9309 and showing it. `src/tests.rs`
//! covers what the suite does not: status codes, the size cap, `Crawl-delay`,
//! `Sitemap` and `Content-Usage`.
//!
//! # Where we go past the RFC, and why
//!
//! Four behaviours here are Google's rather than the RFC's. Each one exists
//! because the strict reading discards a rule a site plainly meant, and
//! discarding a rule means crawling something we were asked not to.
//!
//! - A missing colon is assumed, so `Disallow /private` is a rule. Only for
//!   field names we recognise, which is what stops prose becoming rules.
//! - A user agent value is cut at the first space, so `User-agent: Googlebot
//!   Images` addresses `googlebot`.
//! - `Allow: /dir/index.html` also allows `/dir/`, because those are the same
//!   page on every stock server. Allow only, never `Disallow`.
//! - A line longer than [`MAX_LINE_BYTES`] is truncated rather than dropped.

use std::time::Duration;

mod usage;

pub use usage::{MAX_UNREADABLE, Preference, Usage};

/// The user agent tokens we answer to, in precedence order.
///
/// `umi` first, then the catch all. Nothing else, deliberately: not `umibot`,
/// not `umi/1.0`, not `umi-crawler`. A site that wants to address us has one
/// token to type and it is published on the bot page, and a site that blocks
/// `*` blocks us.
pub const OUR_TOKENS: &[&str] = &["umi", "*"];

/// The parsed size cap from RFC 9309 section 2.5, 500 KiB.
///
/// Bytes past this are ignored rather than treated as an error. Files this
/// large are always generated, and the RFC's answer is to parse what fits.
pub const MAX_BYTES: usize = 500 * 1024;

/// The longest line we keep, in bytes. Anything past this on one line is
/// dropped and the rest of the line is parsed as if it ended there.
///
/// Google's parser uses `2083 * 8 - 1` and the conformance corpus asserts the
/// exact truncation point, so a shorter cap of our own would fail it. Lines
/// this long are always machine generated, and the alternative of dropping the
/// whole line turns a very long `Disallow` into no rule at all, which is the
/// unsafe direction.
pub const MAX_LINE_BYTES: usize = 2083 * 8 - 1;

/// How long a fetched robots.txt stays good, absent a shorter `max-age`.
pub const DEFAULT_TTL: Duration = Duration::from_secs(24 * 60 * 60);

/// Redirect hops followed before giving up, from doc 07.4.
pub const MAX_REDIRECTS: u32 = 5;

/// `Crawl-delay` is clamped into this range.
///
/// The upper clamp matters more than it looks. Some sites publish
/// `Crawl-delay: 86400`, which is a soft block dressed as politeness. Honouring
/// it literally means one page a day forever and a frontier entry that never
/// drains, so the delay is capped and the host is deprioritised instead.
pub const MIN_CRAWL_DELAY: Duration = Duration::from_millis(100);
/// The upper clamp on `Crawl-delay`. See [`MIN_CRAWL_DELAY`].
pub const MAX_CRAWL_DELAY: Duration = Duration::from_secs(300);

/// What a robots.txt says about one path.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Decision {
    /// Crawlable.
    Allowed,
    /// Not crawlable. The coordinator will not lease it.
    Disallowed,
}

impl Decision {
    /// Is this path crawlable.
    #[must_use]
    pub fn is_allowed(self) -> bool {
        matches!(self, Self::Allowed)
    }
}

/// Why a `Robots` has the contents it has.
///
/// Carried into the published robots snapshot in `open-index/umi-robots`, so
/// that a reader can tell "this site allows everything" from "this site was
/// down and we assumed nothing". Those look identical in a decision column and
/// mean completely different things.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Provenance {
    /// A 2xx response that we parsed.
    Parsed,
    /// A 4xx. RFC 9309 section 2.3.1.3: no restrictions.
    NotFound,
    /// A 5xx. RFC 9309 section 2.3.1.4: treat as fully disallowed.
    ServerError,
    /// The fetch failed outright, or redirected past [`MAX_REDIRECTS`].
    Unreachable,
}

/// One `Allow` or `Disallow` rule.
#[derive(Clone, Debug, PartialEq, Eq)]
struct Rule {
    /// The pattern, percent-decoded so it compares against a decoded path.
    pattern: String,
    allow: bool,
    /// Specificity for the precedence rule, in characters of pattern.
    ///
    /// Precomputed because it is compared on every path match and a rule set
    /// can be thousands long.
    length: usize,
}

/// A parsed robots.txt as it applies to one user agent.
#[derive(Clone, Debug)]
pub struct Robots {
    rules: Vec<Rule>,
    crawl_delay: Option<Duration>,
    sitemaps: Vec<String>,
    content_usage: Vec<String>,
    provenance: Provenance,
    /// True when the whole file is a blanket disallow, which lets the frontier
    /// skip a host without walking its rules.
    blanket_disallow: bool,
    /// How many user agent groups the file had, ours and everybody else's.
    groups: u32,
}

impl Robots {
    /// The rules that apply when there is no usable robots.txt: everything is
    /// allowed.
    #[must_use]
    pub fn allow_all(provenance: Provenance) -> Self {
        Self {
            rules: Vec::new(),
            crawl_delay: None,
            sitemaps: Vec::new(),
            content_usage: Vec::new(),
            provenance,
            blanket_disallow: false,
            groups: 0,
        }
    }

    /// The rules that apply when a host is failing: nothing is allowed.
    #[must_use]
    pub fn disallow_all(provenance: Provenance) -> Self {
        Self {
            rules: vec![Rule {
                pattern: "/".to_owned(),
                allow: false,
                length: 1,
            }],
            crawl_delay: None,
            sitemaps: Vec::new(),
            content_usage: Vec::new(),
            provenance,
            blanket_disallow: true,
            groups: 0,
        }
    }

    /// Build the applicable rules from an HTTP status and a body.
    ///
    /// This is the entry point, rather than [`Robots::parse`], because the
    /// status is half the decision and making it a separate call is what lets
    /// someone forget it. RFC 9309 section 2.3.1:
    ///
    /// - 2xx, parse the body
    /// - 3xx, the caller follows up to [`MAX_REDIRECTS`] hops and then treats
    ///   it as unreachable
    /// - 4xx, no restrictions at all
    /// - 5xx, treat as fully disallowed
    ///
    /// The 5xx rule is the one people get wrong, and getting it wrong means
    /// crawling a site hardest at the moment it is least able to serve.
    ///
    /// A 429 goes with the 5xx rather than with the rest of the 4xx, which is
    /// where Google's implementation puts it and where doc 07.6 already puts
    /// it for pages. The status codes are grouped by what the number means and
    /// not by which hundred it is in: a 404 is a site saying it has no rules,
    /// and a 429 is a site saying we are asking too often, which is the last
    /// answer that should turn into permission to crawl the whole host.
    #[must_use]
    pub fn for_status(status: u16, body: &[u8]) -> Self {
        match status {
            200..=299 => Self::parse(body),
            429 => Self::disallow_all(Provenance::ServerError),
            400..=499 => Self::allow_all(Provenance::NotFound),
            500..=599 => Self::disallow_all(Provenance::ServerError),
            // A 1xx or a 3xx that reached here means the caller ran out of
            // redirect hops or saw something it could not classify. Unknown is
            // not the same as permitted.
            _ => Self::disallow_all(Provenance::Unreachable),
        }
    }

    /// Parse a robots.txt body, selecting the group for [`OUR_TOKENS`].
    ///
    /// Bytes past [`MAX_BYTES`] are ignored. Invalid UTF-8 is decoded lossily
    /// rather than rejected, because robots.txt files in the wild carry every
    /// encoding there is and refusing to parse one means treating a site with
    /// rules as a site without.
    #[must_use]
    pub fn parse(body: &[u8]) -> Self {
        let capped = &body[..body.len().min(MAX_BYTES)];
        let text = String::from_utf8_lossy(capped);
        Self::parse_str(&text)
    }

    /// Parse from a string. See [`Robots::parse`].
    #[must_use]
    pub fn parse_str(text: &str) -> Self {
        Self::parse_for(text, OUR_TOKENS)
    }

    /// Parse selecting the group for an arbitrary list of tokens, in
    /// precedence order.
    ///
    /// The crawler always uses [`OUR_TOKENS`]. This exists because the
    /// published robots snapshot in `open-index/umi-robots` is more useful if
    /// it can summarise what a file says about other crawlers too, and because
    /// the RFC 9309 conformance suite is written against arbitrary agents and
    /// a parser that can only answer for itself cannot be run against it.
    ///
    /// A token that is empty, or that contains anything outside
    /// `[A-Za-z0-9_-]`, matches only the `*` group. RFC 9309 section 2.2.1
    /// defines the product token that way, and a caller passing
    /// `Mozilla/5.0 (compatible; ...)` is asking the wrong question.
    #[must_use]
    pub fn parse_for(text: &str, tokens: &[&str]) -> Self {
        // A byte order mark makes the first field name `\u{feff}user-agent`,
        // which quietly drops the first group and, on the very common file
        // that has only one, turns a site's rules into no rules. Plenty of
        // robots.txt files are saved from Windows editors and carry one.
        let text = text.trim_start_matches('\u{feff}');
        // A caller that hands us a full browser user agent string, or an empty
        // one, gets the wildcard group and nothing else. A product token has
        // no slashes, spaces or punctuation in it, and pretending otherwise
        // would have `Mozilla/5.0 (compatible; umi)` match a `umi` group by
        // accident.
        // Lowercased once here, because RFC 9309 section 2.2.1 makes the
        // token comparison case insensitive and the file side is lowercased
        // per line already.
        let usable: Vec<String> = tokens
            .iter()
            .filter(|t| **t == "*" || is_product_token(t))
            .map(|t| t.to_ascii_lowercase())
            .collect();
        let mut best: Option<Group> = None;
        let mut current = Group::new(&usable);
        // A group is a run of user agent lines followed by a run of rule
        // lines. A rule line ends the agent run, and the next agent line after
        // a rule starts a fresh group. Sites get this wrong constantly, so the
        // parser has to be forgiving about blank lines and comments in the
        // middle of a group.
        let mut in_agent_run = false;

        let mut sitemaps = Vec::new();
        let mut content_usage = Vec::new();
        // Every group in the file, not just the one that matched us. The
        // published snapshot reports it so a reader can tell a file that named
        // us specifically from one that gave everybody the same rules, and
        // that comparison needs the count from the whole file.
        let mut groups = 0u32;

        for line in text.lines() {
            let Some((field, value)) = split_line(line) else {
                continue;
            };
            let field = field.to_ascii_lowercase();

            match field.as_str() {
                // Sitemap and Content-Usage are file scoped rather than group
                // scoped, so they are collected regardless of which group is
                // being built.
                "sitemap" => {
                    if !value.is_empty() {
                        sitemaps.push(value.to_owned());
                    }
                    continue;
                }
                "content-usage" => {
                    if !value.is_empty() {
                        content_usage.push(value.to_owned());
                    }
                    continue;
                }
                _ => {}
            }

            if field == "user-agent" {
                if !in_agent_run {
                    // A rule line came before this, so the previous group is
                    // complete.
                    let finished = std::mem::replace(&mut current, Group::new(&usable));
                    best = keep_better(best, finished);
                    in_agent_run = true;
                    // The first user agent line in the file lands here too,
                    // because nothing has started a run yet, so this counts
                    // every group rather than every group after the first.
                    groups = groups.saturating_add(1);
                }
                current.note_agent(value);
                continue;
            }

            match field.as_str() {
                "disallow" => {
                    in_agent_run = false;
                    current.push_rule(value, false);
                }
                "allow" => {
                    in_agent_run = false;
                    current.push_rule(value, true);
                }
                "crawl-delay" => {
                    in_agent_run = false;
                    current.note_crawl_delay(value);
                }
                // Unknown fields are ignored, per RFC 9309 section 2.2.4.
                // Notably that covers `Host` and `Noindex`, both of which have
                // been proposed and neither of which we honour.
                //
                // Ignored means ignored: an unknown line does not end the run
                // of user agent lines either. A file that reads
                // `User-agent: A / Unknown-thing: x / User-agent: B /
                // Disallow: /` names one group covering both agents, because
                // no rule ever separated them, and the RFC says a group is
                // terminated by a user agent line that follows a rule.
                _ => {}
            }
        }
        best = keep_better(best, current);

        let group = best.unwrap_or_else(|| Group::new(&usable));
        let mut rules = group.rules;
        // Sort once at parse time so matching is a linear scan with no
        // allocation. Longest pattern first, and `Allow` before `Disallow` at
        // equal length, which is the RFC's tie break, so the first match wins
        // outright.
        rules.sort_by(|a, b| b.length.cmp(&a.length).then_with(|| b.allow.cmp(&a.allow)));

        let blanket_disallow = rules.len() == 1 && !rules[0].allow && rules[0].pattern == "/";

        Self {
            rules,
            crawl_delay: group.crawl_delay,
            sitemaps,
            content_usage,
            provenance: Provenance::Parsed,
            blanket_disallow,
            groups,
        }
    }

    /// Is this URL crawlable. Takes the whole URL and reduces it to the path,
    /// parameters and query the way [`path_of`] describes.
    ///
    /// This is the call the crawler makes. [`Robots::allows`] is there for
    /// when the path is already in hand.
    #[must_use]
    pub fn allows_url(&self, url: &str) -> Decision {
        self.allows(&path_of(url))
    }

    /// Is `path` crawlable. `path` is the path, parameters and query of a URL,
    /// percent-encoded the way a URL in flight is.
    ///
    /// Comparison is octet by octet against the encoded pattern, which is what
    /// RFC 9309 section 2.2.2 asks for. It is tempting to decode both sides
    /// instead, so that `Disallow: /admin` catches `/%61dmin`, but that is the
    /// canonicaliser's job and it already does it: doc 11.2 step 6 decodes
    /// every unreserved escape, so a path reaching here has no `%61` left to
    /// hide behind. Decoding here as well would additionally make
    /// `Allow: /%62%61%7A` cover `/baz`, which is a different resource and a
    /// permission the site did not give.
    ///
    /// Precedence is longest matching pattern wins, with `Allow` taking ties,
    /// per RFC 9309 section 2.2.2. Nothing matching means allowed, because
    /// robots.txt is a deny list.
    #[must_use]
    pub fn allows(&self, path: &str) -> Decision {
        for rule in &self.rules {
            if matches_pattern(&rule.pattern, path) {
                return if rule.allow {
                    Decision::Allowed
                } else {
                    Decision::Disallowed
                };
            }
        }
        Decision::Allowed
    }

    /// The clamped `Crawl-delay`, if the group declared one.
    ///
    /// Already clamped to [`MIN_CRAWL_DELAY`]..=[`MAX_CRAWL_DELAY`] at parse
    /// time, so a caller cannot forget to.
    #[must_use]
    pub fn crawl_delay(&self) -> Option<Duration> {
        self.crawl_delay
    }

    /// True when the site published a `Crawl-delay` we had to clamp down.
    ///
    /// Doc 07.4 deprioritises these hosts rather than blocking them, so the
    /// scheduler needs to be able to tell a clamped absurd value from a
    /// genuine 300 second delay.
    #[must_use]
    pub fn crawl_delay_was_clamped(&self) -> bool {
        self.crawl_delay == Some(MAX_CRAWL_DELAY)
    }

    /// `Sitemap` lines, in file order.
    ///
    /// Doc 07.4 calls this the highest value line in robots.txt for us, and it
    /// is routinely ignored by crawlers. It feeds the seeding path in doc 13.
    #[must_use]
    pub fn sitemaps(&self) -> &[String] {
        &self.sitemaps
    }

    /// AIPREF `Content-Usage` lines, in file order.
    ///
    /// Recorded and propagated, never acted on for crawl decisions. See doc
    /// 07.5: these express a preference about AI training and our purpose is
    /// index building, so the honest thing is to carry the preference to
    /// downstream users rather than to decide on their behalf.
    #[must_use]
    pub fn content_usage(&self) -> &[String] {
        &self.content_usage
    }

    /// Where these rules came from.
    #[must_use]
    pub fn provenance(&self) -> Provenance {
        self.provenance
    }

    /// True when the whole host is disallowed, so the frontier can skip it
    /// without walking rules per URL.
    #[must_use]
    pub fn is_blanket_disallow(&self) -> bool {
        self.blanket_disallow
    }

    /// How many rules survived parsing. For the published snapshot summary.
    #[must_use]
    pub fn rule_count(&self) -> usize {
        self.rules.len()
    }

    /// How many user agent groups the file had, ours and everybody else's.
    ///
    /// Zero for rules that came from a status rather than a file, and zero for
    /// a file with no `User-agent` line in it at all. The published snapshot
    /// carries it next to [`rule_count`](Self::rule_count), where the pair
    /// says whether a site wrote rules for us or we are reading somebody
    /// else's wildcard group.
    #[must_use]
    pub const fn group_count(&self) -> u32 {
        self.groups
    }
}

/// Is this a product token per RFC 9309 section 2.2.1.
///
/// The RFC writes the grammar as `[A-Za-z_-]+`. Digits are accepted here too,
/// because half the crawlers on the web have a digit in their name and reading
/// the grammar literally would mean refusing to answer for `bingbot2` or
/// `ia_archiver-web.archive.org`.
fn is_product_token(token: &str) -> bool {
    !token.is_empty()
        && token
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-')
}

/// One user agent group while it is being built.
#[derive(Debug)]
struct Group<'a> {
    /// The best match rank any of this group's agent lines scored, where a
    /// lower number is a better match. `None` means no line matched us.
    rank: Option<usize>,
    rules: Vec<Rule>,
    crawl_delay: Option<Duration>,
    /// The tokens we are matching, lowercased, in precedence order.
    tokens: &'a [String],
}

impl<'a> Group<'a> {
    fn new(tokens: &'a [String]) -> Self {
        Self {
            rank: None,
            rules: Vec::new(),
            crawl_delay: None,
            tokens,
        }
    }

    fn note_agent(&mut self, value: &str) {
        // A product token has no spaces in it, but `User-agent: Googlebot
        // Images` is written on real sites all the time and the intent is
        // plainly the first word. Taking the first word means we obey those
        // rules; dropping the line means we ignore them.
        let token = value
            .split_ascii_whitespace()
            .next()
            .unwrap_or("")
            .to_ascii_lowercase();
        // Precedence is by position in the token list, so an explicit `umi`
        // group always beats a `*` group no matter which came first in the
        // file. Each rank names exactly one token, so the lower rank always
        // wins and there is no length tie break to make.
        for (rank, ours) in self.tokens.iter().enumerate() {
            if token == *ours && self.rank.is_none_or(|existing| rank < existing) {
                self.rank = Some(rank);
            }
        }
    }

    fn push_rule(&mut self, value: &str, allow: bool) {
        let value = value.trim();
        // An empty `Disallow:` means allow everything, per RFC 9309 section
        // 2.2.2, and is the conventional way to write a permissive file. An
        // empty `Allow:` has no defined meaning and is ignored.
        if value.is_empty() {
            return;
        }
        let pattern = escape_pattern(value);

        // `Allow: /dir/index.html` is written by people who mean "this
        // directory is fine". Serving `/dir/` and serving `/dir/index.html`
        // is the same page on every stock web server, so the directory gets
        // an `Allow` of its own, anchored so it covers the directory itself
        // and not everything under it.
        //
        // Allow only. Widening a `Disallow` the same way would block pages a
        // site never asked us to block.
        if allow
            && let Some(slash) = pattern.rfind('/')
            && pattern[slash..].starts_with("/index.htm")
        {
            let directory = format!("{}$", &pattern[..=slash]);
            let length = directory.chars().count();
            self.rules.push(Rule {
                pattern: directory,
                allow,
                length,
            });
        }

        let length = pattern.chars().count();
        self.rules.push(Rule {
            pattern,
            allow,
            length,
        });
    }

    fn note_crawl_delay(&mut self, value: &str) {
        let Ok(seconds) = value.trim().parse::<f64>() else {
            return;
        };
        if !seconds.is_finite() || seconds < 0.0 {
            return;
        }
        // Finite is not the same as representable. `Crawl-delay: 1e30` parses
        // to a perfectly ordinary f64 and is more seconds than a `Duration`
        // can hold, and the infallible conversion panics on it. This is not
        // hypothetical: it killed two prefetch runs after a million hosts
        // each, which is a lot of work to lose to one line of somebody's
        // robots.txt. Anything past the ceiling is the ceiling, the same
        // answer `Crawl-delay: 86400` already gets.
        let Ok(raw) = Duration::try_from_secs_f64(seconds) else {
            self.crawl_delay = Some(MAX_CRAWL_DELAY);
            return;
        };
        self.crawl_delay = Some(raw.clamp(MIN_CRAWL_DELAY, MAX_CRAWL_DELAY));
    }
}

/// Keep whichever of two groups applies to us more specifically.
fn keep_better<'a>(best: Option<Group<'a>>, candidate: Group<'a>) -> Option<Group<'a>> {
    let Some(rank) = candidate.rank else {
        return best;
    };
    match best {
        None => Some(candidate),
        Some(current) => {
            let current_rank = current.rank.unwrap_or(usize::MAX);
            match rank.cmp(&current_rank) {
                std::cmp::Ordering::Less => Some(candidate),
                std::cmp::Ordering::Greater => Some(current),
                // Two groups naming the same token. RFC 9309 section 2.2.1
                // says the records are merged.
                std::cmp::Ordering::Equal => {
                    let mut merged = current;
                    merged.rules.extend(candidate.rules);
                    merged.crawl_delay = merged.crawl_delay.or(candidate.crawl_delay);
                    Some(merged)
                }
            }
        }
    }
}

/// The field names we act on. Used to decide whether a line missing its colon
/// is worth reading anyway.
const KNOWN_FIELDS: &[&str] = &[
    "user-agent",
    "useragent",
    "allow",
    "disallow",
    "sitemap",
    "crawl-delay",
    "content-usage",
];

/// Split `field: value`, dropping comments.
///
/// A `#` anywhere starts a comment, which is why a pattern cannot contain one.
/// Returns `None` for blank lines, comment lines, and lines that name no field
/// we recognise.
///
/// The colon is optional when the field name is one we know. Webmasters write
/// `Disallow /private` often enough that treating it as noise means crawling a
/// directory the site told us to leave alone, and there is no other reading of
/// that line. Requiring a known name is what keeps the leniency from turning
/// prose in a comment-free header into rules.
fn split_line(line: &str) -> Option<(&str, &str)> {
    let line = line.split('#').next().unwrap_or("");
    // Truncate rather than drop, on a character boundary so the result is
    // still a string. See [`MAX_LINE_BYTES`].
    let line = if line.len() > MAX_LINE_BYTES {
        let mut cut = MAX_LINE_BYTES;
        while !line.is_char_boundary(cut) {
            cut -= 1;
        }
        &line[..cut]
    } else {
        line
    };

    if let Some((field, value)) = line.split_once(':') {
        let field = field.trim();
        if !field.is_empty() {
            return Some((field, value.trim()));
        }
        return None;
    }

    let line = line.trim();
    let (field, value) = line.split_once([' ', '\t'])?;
    if KNOWN_FIELDS.contains(&field.to_ascii_lowercase().as_str()) {
        return Some((field, value.trim()));
    }
    None
}

/// Match one pattern against one path.
///
/// Two wildcards, from RFC 9309 section 2.2.3. `*` matches any run of
/// characters including none, and `$` at the end of a pattern anchors it to
/// the end of the path. Everything else is a literal prefix match.
fn matches_pattern(pattern: &str, path: &str) -> bool {
    let (pattern, anchored) = match pattern.strip_suffix('$') {
        Some(stem) => (stem, true),
        None => (pattern, false),
    };

    if !pattern.contains('*') {
        return if anchored {
            path == pattern
        } else {
            path.starts_with(pattern)
        };
    }

    // Greedy left to right over the literal runs between wildcards. This is
    // linear in the path per literal and cannot backtrack, which matters
    // because patterns like `/*/*/*/*/*/*.php` show up on real sites and a
    // backtracking matcher turns them into a denial of service against
    // ourselves.
    let mut segments = pattern.split('*');
    let first = segments.next().unwrap_or("");
    if !path.starts_with(first) {
        return false;
    }
    let mut cursor = first.len();
    let mut last_literal = "";
    for segment in segments {
        last_literal = segment;
        if segment.is_empty() {
            continue;
        }
        match path[cursor..].find(segment) {
            Some(offset) => cursor += offset + segment.len(),
            None => return false,
        }
    }

    if !anchored {
        return true;
    }
    // With `$`, the final literal has to land exactly at the end. The greedy
    // scan matched it at the earliest position it could, which may be too
    // early, so check the tail directly instead.
    //
    // That check alone is sufficient. The scan found the leftmost occurrence
    // at or after the previous cursor, so if the path also ends with the
    // literal, that trailing occurrence is at or after the same cursor and is
    // therefore a valid match too. A trailing empty literal means the pattern
    // ended in `*$`, which matches anything.
    last_literal.is_empty() || path.ends_with(last_literal)
}

/// Percent-encode a pattern into the alphabet a URL in flight is written in.
///
/// RFC 9309 section 2.2.2 says octets outside US-ASCII are percent-encoded
/// before comparison, so `Disallow: /caf\u{e9}` has to become `/caf%C3%A9` to
/// stand a chance of matching the path a fetcher would actually request.
/// Existing escapes are left alone apart from having their hex digits
/// uppercased, so that `%2f` and `%2F` are one pattern rather than two.
fn escape_pattern(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = String::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%'
            && i + 2 < bytes.len()
            && bytes[i + 1].is_ascii_hexdigit()
            && bytes[i + 2].is_ascii_hexdigit()
        {
            out.push('%');
            out.push(bytes[i + 1].to_ascii_uppercase() as char);
            out.push(bytes[i + 2].to_ascii_uppercase() as char);
            i += 3;
            continue;
        }
        if bytes[i] >= 0x80 {
            out.push_str(&format!("%{:02X}", bytes[i]));
        } else {
            out.push(bytes[i] as char);
        }
        i += 1;
    }
    out
}

/// The path, parameters and query of a URL, which is the part robots.txt talks
/// about.
///
/// The fragment goes, and anything that does not have a path at all becomes
/// `/`. The input is not required to be a valid URL: robots matching runs on
/// whatever string a link gave us, and refusing to answer for a malformed one
/// would mean crawling it. A string with no recognisable authority is read as
/// having one anyway, so `example.com/a` is a path of `/a`, which matches how
/// people write links and how Google's matcher reads them.
#[must_use]
pub fn path_of(url: &str) -> String {
    let bytes = url.as_bytes();
    // A protocol relative URL starts with two slashes that are authority, not
    // path.
    let search_start = if bytes.starts_with(b"//") { 2 } else { 0 };

    let find_from = |from: usize, set: &[u8]| {
        url.bytes()
            .enumerate()
            .skip(from)
            .find(|(_, b)| set.contains(b))
            .map(|(i, _)| i)
    };

    let early_path = find_from(search_start, b"/?;");
    let scheme_end = url[search_start..].find("://").map(|i| i + search_start);
    // A `://` that appears after the path has begun is inside a query value,
    // not a scheme, as in `/redirect?to=http://elsewhere/`.
    let authority_start = match scheme_end {
        Some(end) if early_path.is_none_or(|p| p >= end) => end + 3,
        _ => search_start,
    };

    let Some(path_start) = find_from(authority_start, b"/?;") else {
        return "/".to_owned();
    };
    let hash = find_from(search_start, b"#");
    if hash.is_some_and(|h| h < path_start) {
        return "/".to_owned();
    }
    let path_end = hash.unwrap_or(url.len());
    let path = &url[path_start..path_end];
    if path.starts_with('/') {
        path.to_owned()
    } else {
        format!("/{path}")
    }
}

#[cfg(test)]
mod tests;
#[cfg(test)]
mod usage_tests;
